export interface AccountTemplate {
  code: string;
  name: string;
  account_type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  parent_code: string | null;
  description: string;
}

/**
 * Czech chart of accounts based on the Czech Accounting Standards (ČÚR / České účetní standardy).
 * Covers account classes 0-7 with key syntetické accounts.
 */
export const czechAccounts: AccountTemplate[] = [
  // ──────────────────────────────────────────────────────────
  // Třída 0 – Dlouhodobý majetek (Long-term assets)
  // ──────────────────────────────────────────────────────────
  {
    code: '013',
    name: 'Software',
    account_type: 'asset',
    parent_code: null,
    description: 'Dlouhodobý nehmotný majetek – software',
  },
  {
    code: '014',
    name: 'Ocenitelná práva',
    account_type: 'asset',
    parent_code: null,
    description: 'Dlouhodobý nehmotný majetek – ocenitelná práva (patenty, licence)',
  },
  {
    code: '019',
    name: 'Ostatní dlouhodobý nehmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Ostatní DNM nezařazený jinde',
  },
  {
    code: '021',
    name: 'Stavby',
    account_type: 'asset',
    parent_code: null,
    description: 'Budovy, haly a stavby',
  },
  {
    code: '022',
    name: 'Hmotné movité věci a jejich soubory',
    account_type: 'asset',
    parent_code: null,
    description: 'Stroje, přístroje, zařízení, dopravní prostředky',
  },
  {
    code: '025',
    name: 'Pěstitelské celky trvalých porostů',
    account_type: 'asset',
    parent_code: null,
    description: 'Sady, vinice, chmelnice a podobné trvalé porosty',
  },
  {
    code: '026',
    name: 'Dospělá zvířata a jejich skupiny',
    account_type: 'asset',
    parent_code: null,
    description: 'Základní stádo a tažná zvířata',
  },
  {
    code: '029',
    name: 'Ostatní dlouhodobý hmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Ostatní DHM nezařazený jinde',
  },
  {
    code: '031',
    name: 'Pozemky',
    account_type: 'asset',
    parent_code: null,
    description: 'Pozemky bez ohledu na výši ocenění',
  },
  {
    code: '032',
    name: 'Umělecká díla a sbírky',
    account_type: 'asset',
    parent_code: null,
    description: 'Umělecká díla, sbírky a předměty kulturní hodnoty',
  },
  {
    code: '041',
    name: 'Nedokončený dlouhodobý nehmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Pořizovaný DNM do doby uvedení do užívání',
  },
  {
    code: '042',
    name: 'Nedokončený dlouhodobý hmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Pořizovaný DHM do doby uvedení do užívání',
  },
  {
    code: '051',
    name: 'Poskytnuté zálohy na dlouhodobý nehmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Zálohy a závdavky na pořízení DNM',
  },
  {
    code: '052',
    name: 'Poskytnuté zálohy na dlouhodobý hmotný majetek',
    account_type: 'asset',
    parent_code: null,
    description: 'Zálohy a závdavky na pořízení DHM',
  },
  {
    code: '073',
    name: 'Oprávky k softwaru',
    account_type: 'asset',
    parent_code: '013',
    description: 'Oprávky (kumulované odpisy) k softwaru',
  },
  {
    code: '074',
    name: 'Oprávky k ocenitelným právům',
    account_type: 'asset',
    parent_code: '014',
    description: 'Oprávky (kumulované odpisy) k ocenitelným právům',
  },
  {
    code: '079',
    name: 'Oprávky k ostatnímu DNM',
    account_type: 'asset',
    parent_code: '019',
    description: 'Oprávky (kumulované odpisy) k ostatnímu DNM',
  },
  {
    code: '081',
    name: 'Oprávky ke stavbám',
    account_type: 'asset',
    parent_code: '021',
    description: 'Oprávky (kumulované odpisy) ke stavbám',
  },
  {
    code: '082',
    name: 'Oprávky k hmotným movitým věcem',
    account_type: 'asset',
    parent_code: '022',
    description: 'Oprávky (kumulované odpisy) k hmotným movitým věcem',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 1 – Zásoby (Inventories)
  // ──────────────────────────────────────────────────────────
  {
    code: '111',
    name: 'Pořízení materiálu',
    account_type: 'asset',
    parent_code: null,
    description: 'Kalkulační účet pro pořízení materiálu (vedlejší pořizovací náklady)',
  },
  {
    code: '112',
    name: 'Materiál na skladě',
    account_type: 'asset',
    parent_code: null,
    description: 'Materiál na skladě v pořizovacích cenách',
  },
  {
    code: '119',
    name: 'Materiál na cestě',
    account_type: 'asset',
    parent_code: null,
    description: 'Materiál fakturovaný, ale dosud nepřijatý na sklad',
  },
  {
    code: '121',
    name: 'Nedokončená výroba',
    account_type: 'asset',
    parent_code: null,
    description: 'Produkty, které prošly jedním nebo více výrobními stupni',
  },
  {
    code: '122',
    name: 'Polotovary vlastní výroby',
    account_type: 'asset',
    parent_code: null,
    description: 'Odděleně evidované polotovary vlastní výroby',
  },
  {
    code: '123',
    name: 'Výrobky',
    account_type: 'asset',
    parent_code: null,
    description: 'Vlastní výrobky na skladě',
  },
  {
    code: '124',
    name: 'Mladá a ostatní zvířata a jejich skupiny',
    account_type: 'asset',
    parent_code: null,
    description: 'Zvířata nezařazená do dlouhodobého majetku',
  },
  {
    code: '131',
    name: 'Pořízení zboží',
    account_type: 'asset',
    parent_code: null,
    description: 'Kalkulační účet pro pořízení zboží',
  },
  {
    code: '132',
    name: 'Zboží na skladě',
    account_type: 'asset',
    parent_code: null,
    description: 'Zboží na skladě a v prodejnách',
  },
  {
    code: '139',
    name: 'Zboží na cestě',
    account_type: 'asset',
    parent_code: null,
    description: 'Zboží fakturované, ale dosud nepřevzaté',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 2 – Krátkodobý finanční majetek a peněžní prostředky
  // ──────────────────────────────────────────────────────────
  {
    code: '211',
    name: 'Pokladna',
    account_type: 'asset',
    parent_code: null,
    description: 'Peníze v hotovosti (korunová i valutová pokladna)',
  },
  {
    code: '213',
    name: 'Ceniny',
    account_type: 'asset',
    parent_code: null,
    description: 'Poštovní známky, kolky, stravenky, telefonní karty',
  },
  {
    code: '221',
    name: 'Bankovní účty',
    account_type: 'asset',
    parent_code: null,
    description: 'Peněžní prostředky na bankovních účtech',
  },
  {
    code: '231',
    name: 'Krátkodobé bankovní úvěry',
    account_type: 'liability',
    parent_code: null,
    description: 'Krátkodobé úvěry poskytnuté bankou (splatnost do 1 roku)',
  },
  {
    code: '232',
    name: 'Eskontní úvěry',
    account_type: 'liability',
    parent_code: null,
    description: 'Úvěry poskytnuté bankou na eskontované směnky',
  },
  {
    code: '241',
    name: 'Emitované krátkodobé dluhopisy',
    account_type: 'liability',
    parent_code: null,
    description: 'Krátkodobé dluhopisy emitované účetní jednotkou',
  },
  {
    code: '249',
    name: 'Ostatní krátkodobé finanční výpomoci',
    account_type: 'liability',
    parent_code: null,
    description: 'Krátkodobé půjčky od nebankovních subjektů',
  },
  {
    code: '251',
    name: 'Majetkové cenné papíry k obchodování',
    account_type: 'asset',
    parent_code: null,
    description: 'Akcie a podíly určené k obchodování',
  },
  {
    code: '253',
    name: 'Dluhové cenné papíry k obchodování',
    account_type: 'asset',
    parent_code: null,
    description: 'Dluhopisy a obdobné CP určené k obchodování',
  },
  {
    code: '261',
    name: 'Peníze na cestě',
    account_type: 'asset',
    parent_code: null,
    description: 'Převody peněz mezi pokladnou a bankou (clearingový účet)',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 3 – Zúčtovací vztahy (Receivables & Payables)
  // ──────────────────────────────────────────────────────────
  {
    code: '311',
    name: 'Odběratelé',
    account_type: 'asset',
    parent_code: null,
    description: 'Pohledávky za odběrateli z obchodních vztahů',
  },
  {
    code: '314',
    name: 'Poskytnuté zálohy – provozní',
    account_type: 'asset',
    parent_code: null,
    description: 'Krátkodobé provozní zálohy poskytnuté dodavatelům',
  },
  {
    code: '315',
    name: 'Ostatní pohledávky',
    account_type: 'asset',
    parent_code: null,
    description: 'Ostatní pohledávky z obchodních vztahů (reklamace apod.)',
  },
  {
    code: '321',
    name: 'Dodavatelé',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči dodavatelům z obchodních vztahů',
  },
  {
    code: '322',
    name: 'Směnky k úhradě',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky ze směnek vydaných dodavatelům',
  },
  {
    code: '324',
    name: 'Přijaté zálohy',
    account_type: 'liability',
    parent_code: null,
    description: 'Krátkodobé zálohy přijaté od odběratelů',
  },
  {
    code: '325',
    name: 'Ostatní závazky',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní závazky z obchodních vztahů',
  },
  {
    code: '331',
    name: 'Zaměstnanci',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči zaměstnancům z pracovního poměru (mzdy)',
  },
  {
    code: '333',
    name: 'Ostatní závazky vůči zaměstnancům',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní závazky vůči zaměstnancům (náhrady, cestovné)',
  },
  {
    code: '335',
    name: 'Pohledávky za zaměstnanci',
    account_type: 'asset',
    parent_code: null,
    description: 'Pohledávky za zaměstnanci (zálohy, manka, škody)',
  },
  {
    code: '336',
    name: 'Zúčtování s institucemi sociálního zabezpečení a zdravotního pojištění',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči OSSZ a zdravotním pojišťovnám',
  },
  {
    code: '341',
    name: 'Daň z příjmů',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazek/pohledávka z titulu daně z příjmů PO/FO',
  },
  {
    code: '342',
    name: 'Ostatní přímé daně',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky z titulu srážkové daně a záloh na daň ze mzdy',
  },
  {
    code: '343',
    name: 'Daň z přidané hodnoty',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazek/pohledávka z DPH',
  },
  {
    code: '345',
    name: 'Ostatní daně a poplatky',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní daňové závazky (silniční, z nemovitostí apod.)',
  },
  {
    code: '351',
    name: 'Pohledávky – ovládající a řídící osoba',
    account_type: 'asset',
    parent_code: null,
    description: 'Pohledávky za propojenými osobami',
  },
  {
    code: '355',
    name: 'Ostatní pohledávky za společníky',
    account_type: 'asset',
    parent_code: null,
    description: 'Ostatní pohledávky za společníky a členy družstva',
  },
  {
    code: '361',
    name: 'Závazky – ovládající a řídící osoba',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči propojeným osobám',
  },
  {
    code: '365',
    name: 'Ostatní závazky ke společníkům',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní závazky ke společníkům a členům družstva',
  },
  {
    code: '381',
    name: 'Náklady příštích období',
    account_type: 'asset',
    parent_code: null,
    description: 'Výdaje běžného období, které patří do nákladů příštích období',
  },
  {
    code: '383',
    name: 'Výdaje příštích období',
    account_type: 'liability',
    parent_code: null,
    description: 'Náklady běžného období, které budou uhrazeny v příštím období',
  },
  {
    code: '384',
    name: 'Výnosy příštích období',
    account_type: 'liability',
    parent_code: null,
    description: 'Příjmy běžného období, které patří do výnosů příštích období',
  },
  {
    code: '385',
    name: 'Příjmy příštích období',
    account_type: 'asset',
    parent_code: null,
    description: 'Výnosy běžného období, za které dosud nebyly přijaty peníze',
  },
  {
    code: '388',
    name: 'Dohadné účty aktivní',
    account_type: 'asset',
    parent_code: null,
    description: 'Pohledávky, u kterých není známa přesná výše nebo datum',
  },
  {
    code: '389',
    name: 'Dohadné účty pasivní',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky, u kterých není známa přesná výše nebo datum',
  },
  {
    code: '391',
    name: 'Opravná položka k pohledávkám',
    account_type: 'asset',
    parent_code: null,
    description: 'Opravné položky snižující hodnotu pohledávek',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 4 – Kapitálové účty a dlouhodobé závazky
  // ──────────────────────────────────────────────────────────
  {
    code: '411',
    name: 'Základní kapitál',
    account_type: 'equity',
    parent_code: null,
    description: 'Základní kapitál obchodní korporace zapsaný v OR',
  },
  {
    code: '412',
    name: 'Ážio',
    account_type: 'equity',
    parent_code: null,
    description: 'Emisní ážio (rozdíl mezi jmenovitou hodnotou a emisním kurzem)',
  },
  {
    code: '413',
    name: 'Ostatní kapitálové fondy',
    account_type: 'equity',
    parent_code: null,
    description: 'Ostatní kapitálové fondy (dary, dotace na kapitál)',
  },
  {
    code: '414',
    name: 'Oceňovací rozdíly z přecenění majetku a závazků',
    account_type: 'equity',
    parent_code: null,
    description: 'Rozdíly z přecenění majetku a závazků reálnou hodnotou',
  },
  {
    code: '421',
    name: 'Rezervní fond',
    account_type: 'equity',
    parent_code: null,
    description: 'Zákonný nebo dobrovolný rezervní fond',
  },
  {
    code: '423',
    name: 'Statutární fondy',
    account_type: 'equity',
    parent_code: null,
    description: 'Fondy tvořené podle stanov společnosti',
  },
  {
    code: '427',
    name: 'Ostatní fondy',
    account_type: 'equity',
    parent_code: null,
    description: 'Ostatní fondy ze zisku',
  },
  {
    code: '428',
    name: 'Nerozdělený zisk minulých let',
    account_type: 'equity',
    parent_code: null,
    description: 'Kumulovaný nerozdělený zisk z předchozích účetních období',
  },
  {
    code: '429',
    name: 'Neuhrazená ztráta minulých let',
    account_type: 'equity',
    parent_code: null,
    description: 'Kumulovaná neuhrazená ztráta z předchozích účetních období',
  },
  {
    code: '431',
    name: 'Výsledek hospodaření ve schvalovacím řízení',
    account_type: 'equity',
    parent_code: null,
    description: 'VH běžného období před rozhodnutím valné hromady o rozdělení',
  },
  {
    code: '451',
    name: 'Rezervy zákonné',
    account_type: 'liability',
    parent_code: null,
    description: 'Rezervy tvořené podle zvláštních právních předpisů',
  },
  {
    code: '453',
    name: 'Rezerva na daň z příjmů',
    account_type: 'liability',
    parent_code: null,
    description: 'Rezerva na očekávanou daňovou povinnost',
  },
  {
    code: '459',
    name: 'Ostatní rezervy',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní provozní a finanční rezervy',
  },
  {
    code: '461',
    name: 'Dlouhodobé bankovní úvěry',
    account_type: 'liability',
    parent_code: null,
    description: 'Bankovní úvěry se splatností delší než 1 rok',
  },
  {
    code: '471',
    name: 'Dlouhodobé závazky – ovládající a řídící osoba',
    account_type: 'liability',
    parent_code: null,
    description: 'Dlouhodobé závazky vůči propojeným osobám',
  },
  {
    code: '479',
    name: 'Ostatní dlouhodobé závazky',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní dlouhodobé závazky nezařazené jinde',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 5 – Náklady (Expenses)
  // ──────────────────────────────────────────────────────────
  {
    code: '501',
    name: 'Spotřeba materiálu',
    account_type: 'expense',
    parent_code: null,
    description: 'Spotřeba materiálu (základní, pomocný, kancelářský apod.)',
  },
  {
    code: '502',
    name: 'Spotřeba energie',
    account_type: 'expense',
    parent_code: null,
    description: 'Spotřeba elektrické energie, plynu, vody, tepla',
  },
  {
    code: '503',
    name: 'Spotřeba ostatních neskladovatelných dodávek',
    account_type: 'expense',
    parent_code: null,
    description: 'Spotřeba neskladovatelných dodávek',
  },
  {
    code: '504',
    name: 'Prodané zboží',
    account_type: 'expense',
    parent_code: null,
    description: 'Pořizovací cena prodaného zboží',
  },
  {
    code: '511',
    name: 'Opravy a udržování',
    account_type: 'expense',
    parent_code: null,
    description: 'Náklady na opravy a údržbu majetku',
  },
  {
    code: '512',
    name: 'Cestovné',
    account_type: 'expense',
    parent_code: null,
    description: 'Cestovní náhrady zaměstnanců',
  },
  {
    code: '513',
    name: 'Náklady na reprezentaci',
    account_type: 'expense',
    parent_code: null,
    description: 'Náklady na reprezentaci (občerstvení, dary)',
  },
  {
    code: '518',
    name: 'Ostatní služby',
    account_type: 'expense',
    parent_code: null,
    description: 'Nájemné, poštovné, telefon, právní služby, audit atd.',
  },
  {
    code: '521',
    name: 'Mzdové náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Hrubé mzdy zaměstnanců',
  },
  {
    code: '522',
    name: 'Příjmy společníků ze závislé činnosti',
    account_type: 'expense',
    parent_code: null,
    description: 'Odměny společníků a jednatelů ze závislé činnosti',
  },
  {
    code: '523',
    name: 'Odměny členům orgánů obchodní korporace',
    account_type: 'expense',
    parent_code: null,
    description: 'Odměny členům představenstva, dozorčí rady apod.',
  },
  {
    code: '524',
    name: 'Zákonné sociální pojištění',
    account_type: 'expense',
    parent_code: null,
    description: 'Sociální a zdravotní pojištění hrazené zaměstnavatelem',
  },
  {
    code: '525',
    name: 'Ostatní sociální pojištění',
    account_type: 'expense',
    parent_code: null,
    description: 'Příspěvky na penzijní připojištění, životní pojištění zaměstnanců',
  },
  {
    code: '527',
    name: 'Zákonné sociální náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Příděl do FKSP, stravování zaměstnanců dle zákona',
  },
  {
    code: '528',
    name: 'Ostatní sociální náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Ostatní sociální náklady nad rámec zákona',
  },
  {
    code: '531',
    name: 'Daň silniční',
    account_type: 'expense',
    parent_code: null,
    description: 'Silniční daň z motorových vozidel',
  },
  {
    code: '532',
    name: 'Daň z nemovitých věcí',
    account_type: 'expense',
    parent_code: null,
    description: 'Daň z nemovitostí (pozemky, stavby)',
  },
  {
    code: '538',
    name: 'Ostatní daně a poplatky',
    account_type: 'expense',
    parent_code: null,
    description: 'Ostatní daně, poplatky, správní a soudní poplatky, kolky',
  },
  {
    code: '541',
    name: 'Zůstatková cena prodaného dlouhodobého nehmotného a hmotného majetku',
    account_type: 'expense',
    parent_code: null,
    description: 'Zůstatková (účetní) cena prodaného dlouhodobého majetku',
  },
  {
    code: '542',
    name: 'Prodaný materiál',
    account_type: 'expense',
    parent_code: null,
    description: 'Pořizovací cena prodaného materiálu',
  },
  {
    code: '543',
    name: 'Dary',
    account_type: 'expense',
    parent_code: null,
    description: 'Poskytnuté dary a příspěvky',
  },
  {
    code: '544',
    name: 'Smluvní pokuty a úroky z prodlení',
    account_type: 'expense',
    parent_code: null,
    description: 'Smluvní pokuty a penále placené dodavatelům',
  },
  {
    code: '545',
    name: 'Ostatní pokuty a penále',
    account_type: 'expense',
    parent_code: null,
    description: 'Pokuty a penále od státních orgánů a institucí',
  },
  {
    code: '546',
    name: 'Odpis pohledávky',
    account_type: 'expense',
    parent_code: null,
    description: 'Jednorázový odpis nedobytné pohledávky',
  },
  {
    code: '548',
    name: 'Ostatní provozní náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Ostatní provozní náklady nezařazené jinde (pojistné, manka)',
  },
  {
    code: '549',
    name: 'Manka a škody z provozní činnosti',
    account_type: 'expense',
    parent_code: null,
    description: 'Manka a škody na majetku z provozní činnosti',
  },
  {
    code: '551',
    name: 'Odpisy dlouhodobého nehmotného a hmotného majetku',
    account_type: 'expense',
    parent_code: null,
    description: 'Účetní odpisy DNM a DHM',
  },
  {
    code: '552',
    name: 'Tvorba a zúčtování rezerv',
    account_type: 'expense',
    parent_code: null,
    description: 'Tvorba a zúčtování zákonných a ostatních rezerv',
  },
  {
    code: '557',
    name: 'Zúčtování oprávky k oceňovacímu rozdílu',
    account_type: 'expense',
    parent_code: null,
    description: 'Odpis oceňovacího rozdílu k nabytému majetku',
  },
  {
    code: '558',
    name: 'Tvorba a zúčtování opravných položek v provozní činnosti',
    account_type: 'expense',
    parent_code: null,
    description: 'Opravné položky k majetku v provozní oblasti',
  },
  {
    code: '562',
    name: 'Úroky',
    account_type: 'expense',
    parent_code: null,
    description: 'Nákladové úroky z úvěrů, půjček a dluhopisů',
  },
  {
    code: '563',
    name: 'Kurzové ztráty',
    account_type: 'expense',
    parent_code: null,
    description: 'Kurzové ztráty z přepočtu cizoměnových operací',
  },
  {
    code: '568',
    name: 'Ostatní finanční náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Bankovní poplatky a ostatní finanční náklady',
  },
  {
    code: '569',
    name: 'Manka a škody na finančním majetku',
    account_type: 'expense',
    parent_code: null,
    description: 'Manka a škody na finančním majetku',
  },
  {
    code: '591',
    name: 'Daň z příjmů z běžné činnosti – splatná',
    account_type: 'expense',
    parent_code: null,
    description: 'Splatná daň z příjmů právnických osob',
  },
  {
    code: '592',
    name: 'Daň z příjmů z běžné činnosti – odložená',
    account_type: 'expense',
    parent_code: null,
    description: 'Odložená daň z příjmů',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 6 – Výnosy (Revenues)
  // ──────────────────────────────────────────────────────────
  {
    code: '601',
    name: 'Tržby za vlastní výrobky',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje vlastních výrobků',
  },
  {
    code: '602',
    name: 'Tržby z prodeje služeb',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje poskytovaných služeb',
  },
  {
    code: '604',
    name: 'Tržby za zboží',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje nakoupeného zboží',
  },
  {
    code: '611',
    name: 'Změna stavu nedokončené výroby',
    account_type: 'revenue',
    parent_code: null,
    description: 'Přírůstky a úbytky nedokončené výroby',
  },
  {
    code: '612',
    name: 'Změna stavu polotovarů vlastní výroby',
    account_type: 'revenue',
    parent_code: null,
    description: 'Přírůstky a úbytky polotovarů vlastní výroby',
  },
  {
    code: '613',
    name: 'Změna stavu výrobků',
    account_type: 'revenue',
    parent_code: null,
    description: 'Přírůstky a úbytky výrobků na skladě',
  },
  {
    code: '621',
    name: 'Aktivace materiálu a zboží',
    account_type: 'revenue',
    parent_code: null,
    description: 'Aktivace materiálu a zboží vyrobených vlastní činností',
  },
  {
    code: '622',
    name: 'Aktivace vnitropodnikových služeb',
    account_type: 'revenue',
    parent_code: null,
    description: 'Aktivace vnitropodnikových služeb (přeprava, opravy)',
  },
  {
    code: '623',
    name: 'Aktivace dlouhodobého nehmotného majetku',
    account_type: 'revenue',
    parent_code: null,
    description: 'Aktivace DNM vytvořeného vlastní činností',
  },
  {
    code: '624',
    name: 'Aktivace dlouhodobého hmotného majetku',
    account_type: 'revenue',
    parent_code: null,
    description: 'Aktivace DHM vytvořeného vlastní činností',
  },
  {
    code: '641',
    name: 'Tržby z prodeje dlouhodobého nehmotného a hmotného majetku',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje dlouhodobého majetku',
  },
  {
    code: '642',
    name: 'Tržby z prodeje materiálu',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje nepotřebného materiálu',
  },
  {
    code: '644',
    name: 'Smluvní pokuty a úroky z prodlení',
    account_type: 'revenue',
    parent_code: null,
    description: 'Přijaté smluvní pokuty a úroky z prodlení od odběratelů',
  },
  {
    code: '646',
    name: 'Výnosy z odepsaných pohledávek',
    account_type: 'revenue',
    parent_code: null,
    description: 'Inkaso dříve odepsaných pohledávek',
  },
  {
    code: '648',
    name: 'Ostatní provozní výnosy',
    account_type: 'revenue',
    parent_code: null,
    description: 'Ostatní provozní výnosy nezařazené jinde',
  },
  {
    code: '662',
    name: 'Úroky',
    account_type: 'revenue',
    parent_code: null,
    description: 'Výnosové úroky z bankovních účtů, půjček, dluhopisů',
  },
  {
    code: '663',
    name: 'Kurzové zisky',
    account_type: 'revenue',
    parent_code: null,
    description: 'Kurzové zisky z přepočtu cizoměnových operací',
  },
  {
    code: '664',
    name: 'Výnosy z přecenění cenných papírů',
    account_type: 'revenue',
    parent_code: null,
    description: 'Výnosy z přecenění cenných papírů reálnou hodnotou',
  },
  {
    code: '668',
    name: 'Ostatní finanční výnosy',
    account_type: 'revenue',
    parent_code: null,
    description: 'Ostatní finanční výnosy nezařazené jinde',
  },

  // ──────────────────────────────────────────────────────────
  // Třída 7 – Závěrkové a podrozvahové účty
  // ──────────────────────────────────────────────────────────
  {
    code: '701',
    name: 'Počáteční účet rozvažný',
    account_type: 'equity',
    parent_code: null,
    description: 'Účet pro otevření účetních knih na počátku období',
  },
  {
    code: '702',
    name: 'Konečný účet rozvažný',
    account_type: 'equity',
    parent_code: null,
    description: 'Účet pro uzavření rozvahových účtů na konci období',
  },
  {
    code: '710',
    name: 'Účet zisků a ztrát',
    account_type: 'equity',
    parent_code: null,
    description: 'Účet pro uzavření výsledkových účtů (náklady a výnosy)',
  },
];
