import type { AccountTemplate } from './czech-accounts';

/**
 * General / simplified chart of accounts for introductory accounting courses.
 * Simple numbering (100-599), basic categories.
 * Names in Czech as this is intended for general coursework in Czech.
 */
export const generalAccounts: AccountTemplate[] = [
  // ──────────────────────────────────────────────────────────
  // 100-199 – Aktiva (Assets)
  // ──────────────────────────────────────────────────────────
  {
    code: '100',
    name: 'Pokladna',
    account_type: 'asset',
    parent_code: null,
    description: 'Peníze v hotovosti',
  },
  {
    code: '110',
    name: 'Banka',
    account_type: 'asset',
    parent_code: null,
    description: 'Peněžní prostředky na bankovních účtech',
  },
  {
    code: '120',
    name: 'Pohledávky z obchodních vztahů',
    account_type: 'asset',
    parent_code: null,
    description: 'Pohledávky za odběrateli za prodané zboží a služby',
  },
  {
    code: '121',
    name: 'Opravná položka k pohledávkám',
    account_type: 'asset',
    parent_code: '120',
    description: 'Opravná položka snižující hodnotu pochybných pohledávek',
  },
  {
    code: '125',
    name: 'Zálohy poskytnuté',
    account_type: 'asset',
    parent_code: null,
    description: 'Zálohy zaplacené dodavatelům',
  },
  {
    code: '126',
    name: 'Ostatní pohledávky',
    account_type: 'asset',
    parent_code: null,
    description: 'Ostatní krátkodobé pohledávky',
  },
  {
    code: '128',
    name: 'Náklady příštích období',
    account_type: 'asset',
    parent_code: null,
    description: 'Předplacené náklady (pojistné, nájemné předem)',
  },
  {
    code: '130',
    name: 'Zásoby – materiál',
    account_type: 'asset',
    parent_code: null,
    description: 'Materiál na skladě',
  },
  {
    code: '131',
    name: 'Zásoby – zboží',
    account_type: 'asset',
    parent_code: null,
    description: 'Zboží na skladě a v prodejnách',
  },
  {
    code: '132',
    name: 'Zásoby – výrobky',
    account_type: 'asset',
    parent_code: null,
    description: 'Vlastní výrobky na skladě',
  },
  {
    code: '133',
    name: 'Nedokončená výroba',
    account_type: 'asset',
    parent_code: null,
    description: 'Rozpracovaná výroba',
  },
  {
    code: '150',
    name: 'Vybavení a zařízení',
    account_type: 'asset',
    parent_code: null,
    description: 'Stroje, přístroje, nábytek a jiný dlouhodobý hmotný majetek',
  },
  {
    code: '151',
    name: 'Budovy',
    account_type: 'asset',
    parent_code: null,
    description: 'Budovy a stavby',
  },
  {
    code: '152',
    name: 'Pozemky',
    account_type: 'asset',
    parent_code: null,
    description: 'Pozemky',
  },
  {
    code: '153',
    name: 'Dopravní prostředky',
    account_type: 'asset',
    parent_code: null,
    description: 'Automobily a jiné dopravní prostředky',
  },
  {
    code: '155',
    name: 'Software',
    account_type: 'asset',
    parent_code: null,
    description: 'Dlouhodobý nehmotný majetek – software',
  },
  {
    code: '160',
    name: 'Oprávky (kumulované odpisy)',
    account_type: 'asset',
    parent_code: null,
    description: 'Oprávky ke dlouhodobému majetku (protiúčet snižující hodnotu)',
  },
  {
    code: '161',
    name: 'Oprávky k budovám',
    account_type: 'asset',
    parent_code: '151',
    description: 'Kumulované odpisy budov',
  },
  {
    code: '162',
    name: 'Oprávky k vybavení',
    account_type: 'asset',
    parent_code: '150',
    description: 'Kumulované odpisy vybavení a zařízení',
  },
  {
    code: '163',
    name: 'Oprávky k dopravním prostředkům',
    account_type: 'asset',
    parent_code: '153',
    description: 'Kumulované odpisy dopravních prostředků',
  },

  // ──────────────────────────────────────────────────────────
  // 200-299 – Závazky (Liabilities)
  // ──────────────────────────────────────────────────────────
  {
    code: '200',
    name: 'Závazky z obchodních vztahů',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči dodavatelům za přijaté zboží a služby',
  },
  {
    code: '205',
    name: 'Směnky k úhradě',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky z vydaných směnek',
  },
  {
    code: '210',
    name: 'Závazky z úvěrů krátkodobé',
    account_type: 'liability',
    parent_code: null,
    description: 'Krátkodobé závazky z úvěrů a půjček (splatnost do 1 roku)',
  },
  {
    code: '215',
    name: 'Zálohy přijaté',
    account_type: 'liability',
    parent_code: null,
    description: 'Zálohy přijaté od odběratelů',
  },
  {
    code: '220',
    name: 'Závazky vůči zaměstnancům',
    account_type: 'liability',
    parent_code: null,
    description: 'Nevyplacené mzdy a platy',
  },
  {
    code: '221',
    name: 'Závazky ze sociálního a zdravotního pojištění',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky vůči OSSZ a zdravotním pojišťovnám',
  },
  {
    code: '222',
    name: 'Daňové závazky',
    account_type: 'liability',
    parent_code: null,
    description: 'Závazky z titulu DPH, daně z příjmů a ostatních daní',
  },
  {
    code: '225',
    name: 'Ostatní závazky',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní krátkodobé závazky',
  },
  {
    code: '230',
    name: 'Výdaje příštích období',
    account_type: 'liability',
    parent_code: null,
    description: 'Náklady zaúčtované, ale dosud neuhrazené',
  },
  {
    code: '235',
    name: 'Výnosy příštích období',
    account_type: 'liability',
    parent_code: null,
    description: 'Přijaté platby za dosud neposkytnuté služby/zboží',
  },
  {
    code: '250',
    name: 'Dlouhodobé úvěry',
    account_type: 'liability',
    parent_code: null,
    description: 'Bankovní úvěry a půjčky se splatností delší než 1 rok',
  },
  {
    code: '260',
    name: 'Ostatní dlouhodobé závazky',
    account_type: 'liability',
    parent_code: null,
    description: 'Ostatní závazky se splatností delší než 1 rok',
  },

  // ──────────────────────────────────────────────────────────
  // 300-399 – Vlastní kapitál (Equity)
  // ──────────────────────────────────────────────────────────
  {
    code: '300',
    name: 'Základní kapitál / Kapitál vlastníka',
    account_type: 'equity',
    parent_code: null,
    description: 'Základní kapitál společnosti nebo vklad vlastníka',
  },
  {
    code: '310',
    name: 'Nerozdělený zisk',
    account_type: 'equity',
    parent_code: null,
    description: 'Kumulovaný nerozdělený zisk z minulých období',
  },
  {
    code: '315',
    name: 'Neuhrazená ztráta',
    account_type: 'equity',
    parent_code: null,
    description: 'Kumulovaná neuhrazená ztráta z minulých období',
  },
  {
    code: '320',
    name: 'Osobní spotřeba / Dividendy',
    account_type: 'equity',
    parent_code: null,
    description: 'Výběry vlastníka nebo vyplacené dividendy',
  },
  {
    code: '330',
    name: 'Rezervní fond',
    account_type: 'equity',
    parent_code: null,
    description: 'Zákonný a dobrovolný rezervní fond',
  },
  {
    code: '340',
    name: 'Výsledek hospodaření běžného roku',
    account_type: 'equity',
    parent_code: null,
    description: 'Zisk nebo ztráta za aktuální účetní období',
  },

  // ──────────────────────────────────────────────────────────
  // 400-499 – Výnosy (Revenue)
  // ──────────────────────────────────────────────────────────
  {
    code: '400',
    name: 'Tržby za zboží',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje zboží',
  },
  {
    code: '410',
    name: 'Tržby za služby',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje poskytovaných služeb',
  },
  {
    code: '420',
    name: 'Úrokové výnosy',
    account_type: 'revenue',
    parent_code: null,
    description: 'Přijaté úroky z bankovních účtů a půjček',
  },
  {
    code: '430',
    name: 'Ostatní výnosy',
    account_type: 'revenue',
    parent_code: null,
    description: 'Ostatní provozní a finanční výnosy',
  },
  {
    code: '431',
    name: 'Tržby z prodeje majetku',
    account_type: 'revenue',
    parent_code: null,
    description: 'Tržby z prodeje dlouhodobého majetku a materiálu',
  },
  {
    code: '435',
    name: 'Kurzové zisky',
    account_type: 'revenue',
    parent_code: null,
    description: 'Kurzové zisky z přepočtu cizoměnových operací',
  },

  // ──────────────────────────────────────────────────────────
  // 500-599 – Náklady (Expenses)
  // ──────────────────────────────────────────────────────────
  {
    code: '500',
    name: 'Náklady na prodané zboží',
    account_type: 'expense',
    parent_code: null,
    description: 'Pořizovací cena prodaného zboží',
  },
  {
    code: '501',
    name: 'Spotřeba materiálu',
    account_type: 'expense',
    parent_code: null,
    description: 'Spotřeba materiálu (základní, pomocný, kancelářský)',
  },
  {
    code: '510',
    name: 'Mzdy a platy',
    account_type: 'expense',
    parent_code: null,
    description: 'Hrubé mzdy a platy zaměstnanců',
  },
  {
    code: '511',
    name: 'Sociální a zdravotní pojištění',
    account_type: 'expense',
    parent_code: null,
    description: 'Sociální a zdravotní pojištění hrazené zaměstnavatelem',
  },
  {
    code: '512',
    name: 'Ostatní osobní náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Stravenky, školení, příspěvky na penzijní pojištění',
  },
  {
    code: '520',
    name: 'Nájemné',
    account_type: 'expense',
    parent_code: null,
    description: 'Nájemné za prostory a vybavení',
  },
  {
    code: '530',
    name: 'Energie',
    account_type: 'expense',
    parent_code: null,
    description: 'Spotřeba elektrické energie, plynu, vody a tepla',
  },
  {
    code: '535',
    name: 'Opravy a údržba',
    account_type: 'expense',
    parent_code: null,
    description: 'Náklady na opravy a udržování majetku',
  },
  {
    code: '536',
    name: 'Cestovné',
    account_type: 'expense',
    parent_code: null,
    description: 'Cestovní náhrady a náklady na služební cesty',
  },
  {
    code: '537',
    name: 'Ostatní služby',
    account_type: 'expense',
    parent_code: null,
    description: 'Poštovné, telefon, právní služby, reklama a jiné služby',
  },
  {
    code: '540',
    name: 'Odpisy',
    account_type: 'expense',
    parent_code: null,
    description: 'Účetní odpisy dlouhodobého majetku',
  },
  {
    code: '550',
    name: 'Úrokové náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Placené úroky z úvěrů a půjček',
  },
  {
    code: '555',
    name: 'Kurzové ztráty',
    account_type: 'expense',
    parent_code: null,
    description: 'Kurzové ztráty z přepočtu cizoměnových operací',
  },
  {
    code: '556',
    name: 'Bankovní poplatky',
    account_type: 'expense',
    parent_code: null,
    description: 'Poplatky za vedení účtu a bankovní služby',
  },
  {
    code: '560',
    name: 'Pojistné',
    account_type: 'expense',
    parent_code: null,
    description: 'Pojistné majetkové, odpovědnostní a jiné',
  },
  {
    code: '570',
    name: 'Daně a poplatky',
    account_type: 'expense',
    parent_code: null,
    description: 'Silniční daň, daň z nemovitostí, správní a soudní poplatky',
  },
  {
    code: '575',
    name: 'Pokuty a penále',
    account_type: 'expense',
    parent_code: null,
    description: 'Smluvní pokuty, penále a sankce',
  },
  {
    code: '580',
    name: 'Ostatní provozní náklady',
    account_type: 'expense',
    parent_code: null,
    description: 'Ostatní provozní náklady nezařazené jinde',
  },
  {
    code: '590',
    name: 'Daň z příjmů',
    account_type: 'expense',
    parent_code: null,
    description: 'Daň z příjmů právnických nebo fyzických osob',
  },
];
