import type { AccountTemplate } from './czech-accounts';

/**
 * IFRS (International Financial Reporting Standards) chart of accounts.
 * Based on standard IAS/IFRS categories. Names in English.
 *
 * Numbering scheme:
 *   1xxx – Assets
 *   2xxx – Liabilities
 *   3xxx – Equity
 *   4xxx – Revenue
 *   5xxx – Expenses
 */
export const ifrsAccounts: AccountTemplate[] = [
  // ──────────────────────────────────────────────────────────
  // 1xxx – Assets
  // ──────────────────────────────────────────────────────────
  {
    code: '1010',
    name: 'Cash and Cash Equivalents',
    account_type: 'asset',
    parent_code: null,
    description: 'Cash on hand, demand deposits, and short-term highly liquid investments (IAS 7)',
  },
  {
    code: '1020',
    name: 'Bank Accounts',
    account_type: 'asset',
    parent_code: null,
    description: 'Current accounts held at financial institutions',
  },
  {
    code: '1050',
    name: 'Short-term Investments',
    account_type: 'asset',
    parent_code: null,
    description: 'Financial assets held for trading or short-term investment (IFRS 9)',
  },
  {
    code: '1100',
    name: 'Trade Receivables',
    account_type: 'asset',
    parent_code: null,
    description: 'Amounts due from customers for goods sold or services rendered (IFRS 15)',
  },
  {
    code: '1110',
    name: 'Allowance for Expected Credit Losses',
    account_type: 'asset',
    parent_code: '1100',
    description: 'Provision for expected credit losses on trade receivables (IFRS 9)',
  },
  {
    code: '1120',
    name: 'Other Receivables',
    account_type: 'asset',
    parent_code: null,
    description: 'Non-trade receivables including tax receivables and advances',
  },
  {
    code: '1130',
    name: 'Prepayments',
    account_type: 'asset',
    parent_code: null,
    description: 'Payments made in advance for goods or services to be received',
  },
  {
    code: '1200',
    name: 'Inventories',
    account_type: 'asset',
    parent_code: null,
    description: 'Raw materials, work in progress, and finished goods (IAS 2)',
  },
  {
    code: '1210',
    name: 'Raw Materials',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Materials to be consumed in the production process',
  },
  {
    code: '1220',
    name: 'Work in Progress',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Goods partially completed in the production process',
  },
  {
    code: '1230',
    name: 'Finished Goods',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Completed goods ready for sale',
  },
  {
    code: '1300',
    name: 'Contract Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Rights to consideration for goods or services transferred (IFRS 15)',
  },
  {
    code: '1400',
    name: 'Current Tax Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Income tax overpayments recoverable (IAS 12)',
  },
  {
    code: '1500',
    name: 'Property, Plant and Equipment',
    account_type: 'asset',
    parent_code: null,
    description: 'Tangible assets held for use in operations (IAS 16)',
  },
  {
    code: '1510',
    name: 'Land',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Land held for use in operations',
  },
  {
    code: '1520',
    name: 'Buildings',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Office buildings, factories, and other structures',
  },
  {
    code: '1530',
    name: 'Machinery and Equipment',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Plant, machinery, tools, and equipment',
  },
  {
    code: '1540',
    name: 'Vehicles',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Motor vehicles and transportation equipment',
  },
  {
    code: '1550',
    name: 'Furniture and Fixtures',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Office furniture, fittings, and fixtures',
  },
  {
    code: '1560',
    name: 'Accumulated Depreciation – PPE',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Cumulative depreciation on property, plant and equipment',
  },
  {
    code: '1600',
    name: 'Intangible Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Identifiable non-monetary assets without physical substance (IAS 38)',
  },
  {
    code: '1610',
    name: 'Goodwill',
    account_type: 'asset',
    parent_code: '1600',
    description: 'Goodwill arising from business combinations (IFRS 3)',
  },
  {
    code: '1620',
    name: 'Software',
    account_type: 'asset',
    parent_code: '1600',
    description: 'Capitalised software development costs',
  },
  {
    code: '1630',
    name: 'Patents and Licences',
    account_type: 'asset',
    parent_code: '1600',
    description: 'Patents, trademarks, licences, and similar rights',
  },
  {
    code: '1640',
    name: 'Accumulated Amortisation – Intangibles',
    account_type: 'asset',
    parent_code: '1600',
    description: 'Cumulative amortisation on intangible assets',
  },
  {
    code: '1700',
    name: 'Right-of-Use Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Lessee right-of-use assets under leases (IFRS 16)',
  },
  {
    code: '1710',
    name: 'Accumulated Depreciation – ROU Assets',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Cumulative depreciation on right-of-use assets',
  },
  {
    code: '1800',
    name: 'Investment Property',
    account_type: 'asset',
    parent_code: null,
    description: 'Property held to earn rental income or for capital appreciation (IAS 40)',
  },
  {
    code: '1900',
    name: 'Deferred Tax Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Tax benefits to be realised in future periods (IAS 12)',
  },

  // ──────────────────────────────────────────────────────────
  // 2xxx – Liabilities
  // ──────────────────────────────────────────────────────────
  {
    code: '2010',
    name: 'Trade Payables',
    account_type: 'liability',
    parent_code: null,
    description: 'Amounts owed to suppliers for goods and services received',
  },
  {
    code: '2020',
    name: 'Accrued Expenses',
    account_type: 'liability',
    parent_code: null,
    description: 'Expenses incurred but not yet paid',
  },
  {
    code: '2030',
    name: 'Other Payables',
    account_type: 'liability',
    parent_code: null,
    description: 'Non-trade payables and sundry creditors',
  },
  {
    code: '2050',
    name: 'Employee Benefits Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Wages, salaries, and other employee benefits payable (IAS 19)',
  },
  {
    code: '2060',
    name: 'Social Security and Tax Withholdings',
    account_type: 'liability',
    parent_code: null,
    description: 'Payroll taxes and social contributions payable',
  },
  {
    code: '2070',
    name: 'VAT Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Value added tax / GST payable to tax authorities',
  },
  {
    code: '2080',
    name: 'Current Tax Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Income tax payable for the current period (IAS 12)',
  },
  {
    code: '2090',
    name: 'Contract Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Obligation to transfer goods/services for consideration received (IFRS 15)',
  },
  {
    code: '2100',
    name: 'Short-term Borrowings',
    account_type: 'liability',
    parent_code: null,
    description: 'Bank overdrafts and short-term loans due within one year',
  },
  {
    code: '2110',
    name: 'Current Portion of Long-term Borrowings',
    account_type: 'liability',
    parent_code: null,
    description: 'Long-term debt maturing within the next 12 months',
  },
  {
    code: '2200',
    name: 'Lease Liabilities – Current',
    account_type: 'liability',
    parent_code: null,
    description: 'Current portion of lease liabilities (IFRS 16)',
  },
  {
    code: '2300',
    name: 'Provisions – Current',
    account_type: 'liability',
    parent_code: null,
    description: 'Short-term provisions for warranties, restructuring, etc. (IAS 37)',
  },
  {
    code: '2500',
    name: 'Long-term Borrowings',
    account_type: 'liability',
    parent_code: null,
    description: 'Bank loans and bonds payable with maturity beyond one year',
  },
  {
    code: '2510',
    name: 'Bonds Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Long-term bonds and debentures issued',
  },
  {
    code: '2600',
    name: 'Lease Liabilities – Non-current',
    account_type: 'liability',
    parent_code: null,
    description: 'Non-current portion of lease liabilities (IFRS 16)',
  },
  {
    code: '2700',
    name: 'Provisions – Non-current',
    account_type: 'liability',
    parent_code: null,
    description: 'Long-term provisions for employee benefits, decommissioning, etc. (IAS 37)',
  },
  {
    code: '2800',
    name: 'Deferred Tax Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Income taxes payable in future periods (IAS 12)',
  },
  {
    code: '2900',
    name: 'Deferred Revenue – Non-current',
    account_type: 'liability',
    parent_code: null,
    description: 'Long-term deferred revenue / advance payments',
  },

  // ──────────────────────────────────────────────────────────
  // 3xxx – Equity
  // ──────────────────────────────────────────────────────────
  {
    code: '3010',
    name: 'Share Capital',
    account_type: 'equity',
    parent_code: null,
    description: 'Nominal/par value of shares issued (IAS 32)',
  },
  {
    code: '3020',
    name: 'Share Premium',
    account_type: 'equity',
    parent_code: null,
    description: 'Amount received in excess of par value on shares issued',
  },
  {
    code: '3030',
    name: 'Treasury Shares',
    account_type: 'equity',
    parent_code: null,
    description: 'Own shares repurchased and held by the entity (contra-equity)',
  },
  {
    code: '3100',
    name: 'Retained Earnings',
    account_type: 'equity',
    parent_code: null,
    description: 'Accumulated undistributed profits or losses',
  },
  {
    code: '3200',
    name: 'Reserves',
    account_type: 'equity',
    parent_code: null,
    description: 'Statutory, legal, and other reserves',
  },
  {
    code: '3210',
    name: 'Revaluation Surplus',
    account_type: 'equity',
    parent_code: '3200',
    description: 'Gains from revaluation of PPE or intangible assets (IAS 16/38)',
  },
  {
    code: '3220',
    name: 'Foreign Currency Translation Reserve',
    account_type: 'equity',
    parent_code: '3200',
    description: 'Exchange differences on translating foreign operations (IAS 21)',
  },
  {
    code: '3230',
    name: 'Hedging Reserve',
    account_type: 'equity',
    parent_code: '3200',
    description: 'Effective portion of gains/losses on hedging instruments (IFRS 9)',
  },
  {
    code: '3300',
    name: 'Profit or Loss for the Period',
    account_type: 'equity',
    parent_code: null,
    description: 'Net profit or loss for the current reporting period',
  },

  // ──────────────────────────────────────────────────────────
  // 4xxx – Revenue
  // ──────────────────────────────────────────────────────────
  {
    code: '4010',
    name: 'Revenue from Contracts with Customers',
    account_type: 'revenue',
    parent_code: null,
    description: 'Revenue recognised under IFRS 15 from sale of goods and services',
  },
  {
    code: '4020',
    name: 'Revenue from Sale of Goods',
    account_type: 'revenue',
    parent_code: '4010',
    description: 'Revenue from sale of physical products',
  },
  {
    code: '4030',
    name: 'Revenue from Rendering of Services',
    account_type: 'revenue',
    parent_code: '4010',
    description: 'Revenue from provision of services',
  },
  {
    code: '4100',
    name: 'Other Income',
    account_type: 'revenue',
    parent_code: null,
    description: 'Income from activities outside the ordinary course of business',
  },
  {
    code: '4110',
    name: 'Gain on Disposal of Assets',
    account_type: 'revenue',
    parent_code: '4100',
    description: 'Gains from sale or disposal of non-current assets',
  },
  {
    code: '4120',
    name: 'Rental Income',
    account_type: 'revenue',
    parent_code: '4100',
    description: 'Rental income from investment property or sub-leasing',
  },
  {
    code: '4200',
    name: 'Finance Income',
    account_type: 'revenue',
    parent_code: null,
    description: 'Interest income, dividend income, and fair value gains on financial assets',
  },
  {
    code: '4210',
    name: 'Interest Income',
    account_type: 'revenue',
    parent_code: '4200',
    description: 'Interest earned on bank deposits, loans, and financial assets',
  },
  {
    code: '4220',
    name: 'Dividend Income',
    account_type: 'revenue',
    parent_code: '4200',
    description: 'Dividends received from investments in equity instruments',
  },
  {
    code: '4230',
    name: 'Foreign Exchange Gains',
    account_type: 'revenue',
    parent_code: '4200',
    description: 'Gains from foreign currency transactions and translation',
  },

  // ──────────────────────────────────────────────────────────
  // 5xxx – Expenses
  // ──────────────────────────────────────────────────────────
  {
    code: '5010',
    name: 'Cost of Sales',
    account_type: 'expense',
    parent_code: null,
    description: 'Direct costs attributable to goods sold or services rendered',
  },
  {
    code: '5020',
    name: 'Raw Materials Consumed',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Cost of raw materials used in production',
  },
  {
    code: '5030',
    name: 'Direct Labour',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Wages of employees directly involved in production',
  },
  {
    code: '5040',
    name: 'Manufacturing Overheads',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Indirect production costs allocated to cost of sales',
  },
  {
    code: '5100',
    name: 'Employee Benefits Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Salaries, wages, social contributions, and other employee costs (IAS 19)',
  },
  {
    code: '5110',
    name: 'Salaries and Wages',
    account_type: 'expense',
    parent_code: '5100',
    description: 'Gross salaries and wages',
  },
  {
    code: '5120',
    name: 'Social Security Contributions',
    account_type: 'expense',
    parent_code: '5100',
    description: 'Employer social security and pension contributions',
  },
  {
    code: '5130',
    name: 'Other Employee Benefits',
    account_type: 'expense',
    parent_code: '5100',
    description: 'Training, insurance, and other staff-related costs',
  },
  {
    code: '5200',
    name: 'Depreciation and Amortisation',
    account_type: 'expense',
    parent_code: null,
    description: 'Depreciation of PPE and amortisation of intangible assets (IAS 16/38)',
  },
  {
    code: '5210',
    name: 'Depreciation – Property, Plant and Equipment',
    account_type: 'expense',
    parent_code: '5200',
    description: 'Systematic allocation of depreciable amount of PPE',
  },
  {
    code: '5220',
    name: 'Amortisation – Intangible Assets',
    account_type: 'expense',
    parent_code: '5200',
    description: 'Systematic allocation of depreciable amount of intangibles',
  },
  {
    code: '5230',
    name: 'Depreciation – Right-of-Use Assets',
    account_type: 'expense',
    parent_code: '5200',
    description: 'Depreciation of right-of-use assets under IFRS 16',
  },
  {
    code: '5240',
    name: 'Impairment Losses',
    account_type: 'expense',
    parent_code: null,
    description: 'Write-down of assets to recoverable amount (IAS 36)',
  },
  {
    code: '5300',
    name: 'Finance Costs',
    account_type: 'expense',
    parent_code: null,
    description: 'Interest expense, lease finance costs, and other borrowing costs',
  },
  {
    code: '5310',
    name: 'Interest Expense',
    account_type: 'expense',
    parent_code: '5300',
    description: 'Interest on loans, bonds, and other borrowings',
  },
  {
    code: '5320',
    name: 'Lease Interest Expense',
    account_type: 'expense',
    parent_code: '5300',
    description: 'Finance cost on lease liabilities (IFRS 16)',
  },
  {
    code: '5330',
    name: 'Foreign Exchange Losses',
    account_type: 'expense',
    parent_code: '5300',
    description: 'Losses from foreign currency transactions and translation',
  },
  {
    code: '5340',
    name: 'Bank Charges',
    account_type: 'expense',
    parent_code: '5300',
    description: 'Bank fees, transaction charges, and other financial service costs',
  },
  {
    code: '5400',
    name: 'Income Tax Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Current and deferred income tax expense (IAS 12)',
  },
  {
    code: '5410',
    name: 'Current Tax Expense',
    account_type: 'expense',
    parent_code: '5400',
    description: 'Income tax payable for the current period',
  },
  {
    code: '5420',
    name: 'Deferred Tax Expense',
    account_type: 'expense',
    parent_code: '5400',
    description: 'Change in deferred tax assets and liabilities',
  },
  {
    code: '5500',
    name: 'Administrative Expenses',
    account_type: 'expense',
    parent_code: null,
    description: 'General and administrative overhead expenses',
  },
  {
    code: '5510',
    name: 'Office Rent',
    account_type: 'expense',
    parent_code: '5500',
    description: 'Rent for office and administrative premises',
  },
  {
    code: '5520',
    name: 'Utilities',
    account_type: 'expense',
    parent_code: '5500',
    description: 'Electricity, water, gas, and heating costs',
  },
  {
    code: '5530',
    name: 'Professional Fees',
    account_type: 'expense',
    parent_code: '5500',
    description: 'Audit, legal, consulting, and other professional fees',
  },
  {
    code: '5540',
    name: 'Insurance',
    account_type: 'expense',
    parent_code: '5500',
    description: 'Business insurance premiums',
  },
  {
    code: '5550',
    name: 'Office Supplies',
    account_type: 'expense',
    parent_code: '5500',
    description: 'Stationery, consumables, and other office supplies',
  },
  {
    code: '5600',
    name: 'Selling and Distribution Expenses',
    account_type: 'expense',
    parent_code: null,
    description: 'Marketing, advertising, and distribution costs',
  },
  {
    code: '5610',
    name: 'Advertising and Marketing',
    account_type: 'expense',
    parent_code: '5600',
    description: 'Advertising, promotion, and marketing campaign costs',
  },
  {
    code: '5620',
    name: 'Freight and Delivery',
    account_type: 'expense',
    parent_code: '5600',
    description: 'Shipping, freight, and delivery costs for goods sold',
  },
  {
    code: '5700',
    name: 'Other Expenses',
    account_type: 'expense',
    parent_code: null,
    description: 'Miscellaneous expenses not classified elsewhere',
  },
  {
    code: '5710',
    name: 'Loss on Disposal of Assets',
    account_type: 'expense',
    parent_code: '5700',
    description: 'Losses from sale or disposal of non-current assets',
  },
  {
    code: '5720',
    name: 'Donations and Contributions',
    account_type: 'expense',
    parent_code: '5700',
    description: 'Charitable donations and contributions',
  },
];
