import type { AccountTemplate } from './czech-accounts';

/**
 * US GAAP (Generally Accepted Accounting Principles) chart of accounts.
 * Based on standard US numbering conventions. Names in English.
 *
 * Numbering scheme:
 *   1xxx – Assets
 *   2xxx – Liabilities
 *   3xxx – Equity
 *   4xxx – Revenue
 *   5xxx – Cost of Goods Sold
 *   6xxx – Operating Expenses
 *   7xxx – Other Expenses (Interest, Taxes)
 */
export const usgaapAccounts: AccountTemplate[] = [
  // ──────────────────────────────────────────────────────────
  // 1xxx – Assets
  // ──────────────────────────────────────────────────────────
  {
    code: '1010',
    name: 'Cash',
    account_type: 'asset',
    parent_code: null,
    description: 'Cash on hand and in bank accounts (ASC 305)',
  },
  {
    code: '1020',
    name: 'Petty Cash',
    account_type: 'asset',
    parent_code: null,
    description: 'Small cash fund for minor expenditures',
  },
  {
    code: '1030',
    name: 'Cash Equivalents',
    account_type: 'asset',
    parent_code: null,
    description: 'Short-term highly liquid investments (maturity ≤ 3 months)',
  },
  {
    code: '1050',
    name: 'Short-term Investments',
    account_type: 'asset',
    parent_code: null,
    description: 'Marketable securities and short-term investments (ASC 320)',
  },
  {
    code: '1100',
    name: 'Accounts Receivable',
    account_type: 'asset',
    parent_code: null,
    description: 'Trade receivables from customers for goods/services sold (ASC 310)',
  },
  {
    code: '1110',
    name: 'Allowance for Doubtful Accounts',
    account_type: 'asset',
    parent_code: '1100',
    description: 'Estimated uncollectible accounts receivable (contra asset)',
  },
  {
    code: '1120',
    name: 'Notes Receivable',
    account_type: 'asset',
    parent_code: null,
    description: 'Promissory notes receivable from borrowers',
  },
  {
    code: '1130',
    name: 'Interest Receivable',
    account_type: 'asset',
    parent_code: null,
    description: 'Accrued interest income not yet received',
  },
  {
    code: '1140',
    name: 'Employee Advances',
    account_type: 'asset',
    parent_code: null,
    description: 'Advances and loans to employees',
  },
  {
    code: '1150',
    name: 'Prepaid Expenses',
    account_type: 'asset',
    parent_code: null,
    description: 'Payments made in advance for future expenses (insurance, rent)',
  },
  {
    code: '1200',
    name: 'Inventory',
    account_type: 'asset',
    parent_code: null,
    description: 'Merchandise, raw materials, WIP, and finished goods (ASC 330)',
  },
  {
    code: '1210',
    name: 'Raw Materials Inventory',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Raw materials awaiting use in production',
  },
  {
    code: '1220',
    name: 'Work-in-Process Inventory',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Partially completed goods in production',
  },
  {
    code: '1230',
    name: 'Finished Goods Inventory',
    account_type: 'asset',
    parent_code: '1200',
    description: 'Completed products ready for sale',
  },
  {
    code: '1300',
    name: 'Other Current Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Miscellaneous current assets not classified elsewhere',
  },
  {
    code: '1500',
    name: 'Property, Plant and Equipment',
    account_type: 'asset',
    parent_code: null,
    description: 'Long-lived tangible assets used in operations (ASC 360)',
  },
  {
    code: '1510',
    name: 'Land',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Land and land improvements (non-depreciable)',
  },
  {
    code: '1520',
    name: 'Buildings',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Office buildings, warehouses, factories',
  },
  {
    code: '1530',
    name: 'Machinery and Equipment',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Machinery, tools, and production equipment',
  },
  {
    code: '1540',
    name: 'Vehicles',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Automobiles, trucks, and other vehicles',
  },
  {
    code: '1550',
    name: 'Furniture and Fixtures',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Office furniture, shelving, and fixtures',
  },
  {
    code: '1560',
    name: 'Computer Equipment',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Computers, servers, and IT hardware',
  },
  {
    code: '1570',
    name: 'Leasehold Improvements',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Improvements to leased property',
  },
  {
    code: '1600',
    name: 'Accumulated Depreciation',
    account_type: 'asset',
    parent_code: '1500',
    description: 'Cumulative depreciation on PP&E (contra asset)',
  },
  {
    code: '1700',
    name: 'Intangible Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Non-physical long-lived assets (ASC 350)',
  },
  {
    code: '1710',
    name: 'Goodwill',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Goodwill from business combinations (ASC 805)',
  },
  {
    code: '1720',
    name: 'Patents',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Patent rights and associated costs',
  },
  {
    code: '1730',
    name: 'Trademarks',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Trademark rights and associated costs',
  },
  {
    code: '1740',
    name: 'Software',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Capitalised internal-use software (ASC 350-40)',
  },
  {
    code: '1750',
    name: 'Accumulated Amortisation',
    account_type: 'asset',
    parent_code: '1700',
    description: 'Cumulative amortisation on intangible assets (contra asset)',
  },
  {
    code: '1800',
    name: 'Operating Lease Right-of-Use Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Right-of-use assets under operating leases (ASC 842)',
  },
  {
    code: '1900',
    name: 'Deferred Tax Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Future tax benefits from deductible temporary differences (ASC 740)',
  },
  {
    code: '1950',
    name: 'Other Non-current Assets',
    account_type: 'asset',
    parent_code: null,
    description: 'Security deposits, long-term receivables, and other non-current assets',
  },

  // ──────────────────────────────────────────────────────────
  // 2xxx – Liabilities
  // ──────────────────────────────────────────────────────────
  {
    code: '2010',
    name: 'Accounts Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Trade payables to suppliers for goods and services',
  },
  {
    code: '2020',
    name: 'Notes Payable – Short-term',
    account_type: 'liability',
    parent_code: null,
    description: 'Short-term promissory notes and commercial paper',
  },
  {
    code: '2050',
    name: 'Accrued Wages and Salaries',
    account_type: 'liability',
    parent_code: null,
    description: 'Wages and salaries earned but not yet paid',
  },
  {
    code: '2060',
    name: 'Payroll Taxes Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'FICA, federal and state withholding taxes payable',
  },
  {
    code: '2070',
    name: 'Sales Tax Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Collected sales tax owed to government',
  },
  {
    code: '2080',
    name: 'Income Tax Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Federal and state income tax payable (ASC 740)',
  },
  {
    code: '2090',
    name: 'Interest Payable',
    account_type: 'liability',
    parent_code: null,
    description: 'Accrued interest expense not yet paid',
  },
  {
    code: '2100',
    name: 'Accrued Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Other accrued expenses and liabilities',
  },
  {
    code: '2110',
    name: 'Unearned Revenue',
    account_type: 'liability',
    parent_code: null,
    description: 'Revenue collected but not yet earned (ASC 606)',
  },
  {
    code: '2120',
    name: 'Customer Deposits',
    account_type: 'liability',
    parent_code: null,
    description: 'Deposits received from customers',
  },
  {
    code: '2150',
    name: 'Current Portion of Long-term Debt',
    account_type: 'liability',
    parent_code: null,
    description: 'Long-term debt maturing within the next 12 months',
  },
  {
    code: '2200',
    name: 'Current Operating Lease Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Current portion of operating lease liabilities (ASC 842)',
  },
  {
    code: '2500',
    name: 'Long-term Debt',
    account_type: 'liability',
    parent_code: null,
    description: 'Bank loans, bonds, and notes payable due beyond one year',
  },
  {
    code: '2510',
    name: 'Bonds Payable',
    account_type: 'liability',
    parent_code: '2500',
    description: 'Long-term bonds issued by the company',
  },
  {
    code: '2520',
    name: 'Mortgage Payable',
    account_type: 'liability',
    parent_code: '2500',
    description: 'Long-term mortgage on property',
  },
  {
    code: '2600',
    name: 'Non-current Operating Lease Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Non-current portion of operating lease liabilities (ASC 842)',
  },
  {
    code: '2700',
    name: 'Deferred Tax Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Taxes payable in future periods from taxable temporary differences (ASC 740)',
  },
  {
    code: '2800',
    name: 'Other Long-term Liabilities',
    account_type: 'liability',
    parent_code: null,
    description: 'Pension obligations, deferred compensation, and other long-term liabilities',
  },

  // ──────────────────────────────────────────────────────────
  // 3xxx – Equity
  // ──────────────────────────────────────────────────────────
  {
    code: '3010',
    name: 'Common Stock',
    account_type: 'equity',
    parent_code: null,
    description: 'Par value of common shares issued and outstanding',
  },
  {
    code: '3020',
    name: 'Preferred Stock',
    account_type: 'equity',
    parent_code: null,
    description: 'Par value of preferred shares issued and outstanding',
  },
  {
    code: '3100',
    name: 'Retained Earnings',
    account_type: 'equity',
    parent_code: null,
    description: 'Accumulated net income less dividends declared',
  },
  {
    code: '3200',
    name: 'Additional Paid-in Capital',
    account_type: 'equity',
    parent_code: null,
    description: 'Amount received in excess of par value on stock issuance',
  },
  {
    code: '3300',
    name: 'Treasury Stock',
    account_type: 'equity',
    parent_code: null,
    description: 'Cost of repurchased company shares (contra equity)',
  },
  {
    code: '3400',
    name: 'Accumulated Other Comprehensive Income',
    account_type: 'equity',
    parent_code: null,
    description: 'Unrealised gains/losses, foreign currency adjustments, pension adjustments (ASC 220)',
  },
  {
    code: '3500',
    name: 'Dividends Declared',
    account_type: 'equity',
    parent_code: null,
    description: 'Dividends declared to shareholders (reduces retained earnings)',
  },

  // ──────────────────────────────────────────────────────────
  // 4xxx – Revenue
  // ──────────────────────────────────────────────────────────
  {
    code: '4010',
    name: 'Sales Revenue',
    account_type: 'revenue',
    parent_code: null,
    description: 'Revenue from sale of goods (ASC 606)',
  },
  {
    code: '4020',
    name: 'Sales Returns and Allowances',
    account_type: 'revenue',
    parent_code: '4010',
    description: 'Returns and allowances reducing gross sales (contra revenue)',
  },
  {
    code: '4030',
    name: 'Sales Discounts',
    account_type: 'revenue',
    parent_code: '4010',
    description: 'Early payment discounts granted to customers (contra revenue)',
  },
  {
    code: '4100',
    name: 'Service Revenue',
    account_type: 'revenue',
    parent_code: null,
    description: 'Revenue from rendering services',
  },
  {
    code: '4200',
    name: 'Interest Income',
    account_type: 'revenue',
    parent_code: null,
    description: 'Interest earned on investments, loans, and deposits',
  },
  {
    code: '4300',
    name: 'Dividend Income',
    account_type: 'revenue',
    parent_code: null,
    description: 'Dividends received from investments',
  },
  {
    code: '4400',
    name: 'Gain on Sale of Assets',
    account_type: 'revenue',
    parent_code: null,
    description: 'Gains from disposal of long-lived assets (ASC 360)',
  },
  {
    code: '4500',
    name: 'Other Revenue',
    account_type: 'revenue',
    parent_code: null,
    description: 'Miscellaneous revenue not classified elsewhere',
  },

  // ──────────────────────────────────────────────────────────
  // 5xxx – Cost of Goods Sold
  // ──────────────────────────────────────────────────────────
  {
    code: '5010',
    name: 'Cost of Goods Sold',
    account_type: 'expense',
    parent_code: null,
    description: 'Direct cost of goods sold during the period',
  },
  {
    code: '5020',
    name: 'Purchases',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Purchases of raw materials and merchandise for resale',
  },
  {
    code: '5030',
    name: 'Purchase Returns and Allowances',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Returns and allowances reducing purchases (contra expense)',
  },
  {
    code: '5040',
    name: 'Freight-in',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Transportation costs on incoming inventory',
  },
  {
    code: '5050',
    name: 'Direct Labour',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Wages of production workers',
  },
  {
    code: '5060',
    name: 'Manufacturing Overhead',
    account_type: 'expense',
    parent_code: '5010',
    description: 'Indirect manufacturing costs (factory rent, utilities, supervision)',
  },

  // ──────────────────────────────────────────────────────────
  // 6xxx – Operating Expenses
  // ──────────────────────────────────────────────────────────
  {
    code: '6010',
    name: 'Salaries and Wages Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Gross salaries and wages for non-production employees',
  },
  {
    code: '6020',
    name: 'Payroll Tax Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Employer FICA, FUTA, SUTA, and other payroll taxes',
  },
  {
    code: '6030',
    name: 'Employee Benefits Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Health insurance, 401(k) match, and other benefits',
  },
  {
    code: '6100',
    name: 'Rent Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Office and facility rent (short-term / variable leases)',
  },
  {
    code: '6110',
    name: 'Utilities Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Electricity, gas, water, and other utilities',
  },
  {
    code: '6120',
    name: 'Telephone and Internet',
    account_type: 'expense',
    parent_code: null,
    description: 'Telephone service, internet, and communication costs',
  },
  {
    code: '6130',
    name: 'Office Supplies Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Stationery, toner, and general office supplies',
  },
  {
    code: '6140',
    name: 'Postage and Shipping',
    account_type: 'expense',
    parent_code: null,
    description: 'Postage, courier, and outbound shipping costs',
  },
  {
    code: '6150',
    name: 'Insurance Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Business insurance premiums (property, liability, etc.)',
  },
  {
    code: '6160',
    name: 'Repairs and Maintenance',
    account_type: 'expense',
    parent_code: null,
    description: 'Maintenance and repair costs for equipment and facilities',
  },
  {
    code: '6170',
    name: 'Travel Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Business travel, lodging, and meals',
  },
  {
    code: '6180',
    name: 'Advertising Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Advertising, marketing, and promotional costs (ASC 720-35)',
  },
  {
    code: '6190',
    name: 'Professional Fees',
    account_type: 'expense',
    parent_code: null,
    description: 'Legal, accounting, consulting, and audit fees',
  },
  {
    code: '6200',
    name: 'Depreciation Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Depreciation of property, plant, and equipment (ASC 360)',
  },
  {
    code: '6210',
    name: 'Amortisation Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Amortisation of intangible assets (ASC 350)',
  },
  {
    code: '6300',
    name: 'Bad Debt Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Estimated uncollectible accounts expense (ASC 326)',
  },
  {
    code: '6400',
    name: 'Miscellaneous Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Miscellaneous operating expenses not classified elsewhere',
  },

  // ──────────────────────────────────────────────────────────
  // 7xxx – Other Expenses (Interest, Taxes, Non-operating)
  // ──────────────────────────────────────────────────────────
  {
    code: '7010',
    name: 'Interest Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Interest on loans, bonds, and other borrowings',
  },
  {
    code: '7020',
    name: 'Loss on Sale of Assets',
    account_type: 'expense',
    parent_code: null,
    description: 'Losses from disposal of long-lived assets',
  },
  {
    code: '7030',
    name: 'Foreign Exchange Loss',
    account_type: 'expense',
    parent_code: null,
    description: 'Losses from foreign currency transactions',
  },
  {
    code: '7100',
    name: 'Income Tax Expense',
    account_type: 'expense',
    parent_code: null,
    description: 'Federal and state income tax expense (ASC 740)',
  },
  {
    code: '7110',
    name: 'Deferred Income Tax Expense',
    account_type: 'expense',
    parent_code: '7100',
    description: 'Change in deferred tax assets and liabilities',
  },
];
